### ISSUE TITLE
[GET-39] Use Code for America Gem Design

### ISSUE THREAD

**Issue by HiGregory** [gethousing/gethousing_app#1]
This project form should use Code for America Style Guide or Design which is in gem form. [GET-39]

Example: This is also a test. 

[GET-39]: https://housing.atlassian.net/browse/GET-39

**Comment by HiGregory** [comment]
See example @EOOkuro .

**Comment by EOOkuro** [comment]
Received

**Comment by whitneylubin** [comment]
Gotcha

**Comment by whitneylubin** [comment]
![issues#1](https://user-images.githubusercontent.com/39642663/63041854-c6220180-be96-11e9-906f-29f26b9c9fff.png)
