### ISSUE TITLE
AirBnb React Component Search Filter for Rails Resources Model

### ISSUE THREAD

**Issue by whitneylubin** [gethousing/gethousing_app#2]
Might want to use ElasticSearch. Complexity Score Range(1-5) : Complexity Score: 5

API endpoint:

"/api/v1/resources"

Attributes-
        name:string
        address:string
        city:string
        zipcode:string
        rent: boolean,
        buy: boolean,
        homeless: boolean,
        parent: boolean,
        student: boolean,
        senior: boolean,
        veteran: boolean,

**Comment by HiGregory** [comment]
This has been added in a sprint from several weeks back in-testing. Closing.
