### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by whitneylubin** [gethousing/gethousing_app#20]
Admin should be able to create a form for developers to fill.

**Comment by HiGregory** [comment]
@HiGregory is assigned to do user testing on local or test environment.

URL Path --> localhost:3000/a_addarental

How To
1. Go to App.js to find the URL path (Add a Rental)
2. Setup local and enter information

Deliverables --> Get a snapshot of this working

**Comment by HiGregory** [comment]
This feature has been added to the GetHousing Mobile where GetHousing Web will be the dashboard for data collected for end-users. Closing.
